drive:
    ros__parameters:
        visualization: true
        model_path: "/lanefollowing/ros2_ws/src/lane_following/model/model.h5"
        object_model_path: "/lanefollowing/ros2_ws/src/lane_following/model/yolo.h5"
